<?xml version="1.0" encoding="UTF-8"?>

<xsl:stylesheet 
    xmlns:rng="http://relaxng.org/ns/structure/1.0"
    xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
    xmlns:xs="http://www.w3.org/2001/XMLSchema"
    xmlns:xlink="http://www.w3.org/1999/xlink"
    version="3.0"
    exclude-result-prefixes="rng xsl">
    
    <xsl:output xml:space="default" indent="yes"/>
    
    <!-- Produces a list of elements and their attributes from relax RNG schema -->
    
    <!-- 
        Green list of elements that will occur in the output
        If string is empty then no filter will be applied.
    -->
    <!-- 
        List generated from MEI_attr_list.xml - https://github.com/Edirom/MerMEId/blob/8a8c054c232d5618f94b585e42a7c2c19485adf1/forms/model/MEI_attr_list.xml
        adapted for MEI 5.0, removed obsolete elements (fingerprint, pgFoot2, pgHead2)
    -->
    <xsl:param name="element-filter" as="xs:string">
       abbr
       accMat
       accessRestrict
       accid
       acquisition
       actor
       add
       addDesc
       addName
       addrLine
       address
       altId
       ambNote
       ambitus
       analytic
       anchoredText
       annot
       app
       appInfo
       application
       argument
       arranger
       attUsage
       audience
       author
       avFile
       availability
       back
       bibl
       biblList
       biblScope
       biblStruct
       bifolium
       binding
       bindingDesc
       bloc
       body
       byline
       caption
       captureMode
       carrierForm
       castGrp
       castItem
       castList
       catRel
       catchwords
       category
       cb
       change
       changeDesc
       choice
       classDecls
       classification
       clip
       colLayout
       collation
       colophon
       componentList
       composer
       condition
       contentItem
       contents
       context
       contributor
       corpName
       corr
       correction
       country
       creation
       cutout
       damage
       date
       decoDesc
       decoNote
       dedicatee
       dedication
       del
       depth
       desc
       dim
       dimensions
       distributor
       district
       div
       domainsDecl
       edition
       editionStmt
       editor
       editorialDecl
       encodingDesc
       epigraph
       event
       eventList
       exhibHist
       expan
       expansion
       explicit
       expression
       expressionList
       extMeta
       extent
       facsimile
       famName
       fermata
       fig
       figDesc
       fileChar
       fileDesc
       foliaDesc
       foliation
       folium
       foreName
       front
       funder
       gap
       genDesc
       genName
       genState
       genre
       geogFeat
       geogName
       graphic
       group
       hand
       handList
       handShift
       head
       height
       heraldry
       hex
       history
       identifier
       imprimatur
       imprint
       incip
       incipCode
       incipText
       inscription
       instrGrp
       interpretation
       item
       itemList
       key
       keyAccid
       keySig
       label
       labelAbbr
       langUsage
       language
       layout
       layoutDesc
       lem
       li
       librettist
       line
       list
       locus
       locusGrp
       lv
       lyricist
       manifestation
       manifestationList
       mapping
       mei
       meiCorpus
       meiHead
       mensuration
       metaMark
       metaText
       meter
       meterSig
       meterSigGrp
       monogr
       music
       name
       nameLink
       namespace
       normalization
       notesStmt
       orig
       otherChar
       p
       pad
       patch
       perfDuration
       perfMedium
       perfRes
       perfResList
       performance
       periodName
       persName
       pgDesc
       pgFoot
       pgHead
       phrase
       physDesc
       physLoc
       physMedium
       plateNum
       playingSpeed
       postBox
       postCode
       price
       prog
       projectDesc
       propName
       propValue
       provenance
       ptr
       pubPlace
       pubStmt
       publisher
       q
       quote
       rdg
       recipient
       recording
       ref
       refrain
       reg
       region
       relatedItem
       relation
       relationList
       rend
       repository
       resp
       respStmt
       restore
       revisionDesc
       role
       roleDesc
       roleName
       rubric
       samplingDecl
       scoreFormat
       scriptDesc
       scriptNote
       seal
       sealDesc
       secFolio
       seg
       segmentation
       seqNum
       series
       seriesStmt
       settlement
       sic
       signatures
       source
       sourceDesc
       speaker
       specRepro
       sponsor
       stack
       stamp
       stdVals
       street
       styleName
       subst
       supplied
       support
       supportDesc
       surface
       symName
       symProp
       symbol
       symbolDef
       symbolTable
       sysReq
       table
       tagUsage
       tagsDecl
       taxonomy
       td
       tempo
       term
       termList
       textLang
       th
       title
       titlePage
       titlePart
       titleStmt
       tr
       trackConfig
       treatHist
       treatSched
       typeDesc
       typeNote
       unclear
       unpub
       useRestrict
       watermark
       when
       width
       work
       workList
       zone
    </xsl:param>
    
    <xsl:template match="/">
        <elements xmlns:xlink="http://www.w3.org/1999/xlink">
            <xsl:apply-templates select="descendant::rng:element[@name and not(contains(parent::*/@name,'svg_')) and (if($element-filter) then @name=tokenize(normalize-space($element-filter), '\s+') else true())]"/>
        </elements>
    </xsl:template>
    
    <xsl:template match="rng:element">
        <xsl:text>
        </xsl:text>
        <xsl:element name="{@name}">
            <xsl:apply-templates select="rng:ref[contains(@name,'att.') or contains(@name,'attlist')]"/>
            <xsl:apply-templates select="descendant::rng:attribute"/>            
        </xsl:element>
    </xsl:template>
    
    <xsl:template match="rng:ref[@name]">
        <xsl:variable name="defName"><xsl:value-of select="@name"/></xsl:variable>
        <xsl:apply-templates select="/*/rng:define[@name=$defName]"/>
    </xsl:template>
    
    <xsl:template match="rng:define">
        <xsl:apply-templates select="rng:ref[contains(@name,'att.') or contains(@name,'attlist')]"/>
        <xsl:apply-templates select="descendant::rng:attribute"/>
    </xsl:template>
    
    <xsl:template match="rng:attribute[@name]">
        <xsl:attribute name="{@name}"/>
    </xsl:template>
    
</xsl:stylesheet>